### ISSUE TITLE
Label l1 l2 PNs

### ISSUE THREAD

**Issue by schlegelp** [flyconnectome/hemibrain_olf_data#9]
l1PNs (`AVM02^A12`)
```
1734350908, 1765040289,  754534424,  754538881, 1734350788, 722817260, 5813039315,
1796818119, 1827516355, 1796817841, 818983130, 1797505019, 1609542060, 1609883245,
1640568102, 542634818, 5901222910,  630714299,  697485362,  635416407, 1630051981,  
574374051,  574037281,  574032862, 5813050729, 1882083076, 5813055180,  606090268, 
1850706912, 1850711304, 850703925, 1917188956,  850708902, 5812983069, 5813024799, 
1887163927, 1693486219, 1827861966, 1825085656, 1857148391, 1856833015, 1630734360, 
5813044177,  819993149
```

l2PNs (`AVM03^A13`)
```
666818300, 1671638278, 1793403571, 1917866877, 1700307582, 1037293275, 1733677514, 
1794055377, 1723506321, 1661769627, 1755556277, 1727979406, 5901222731, 2065197353, 
2038617453, 2069644133, 1225100939, 1788676257, 5813069447, 5813056072, 1789013008, 
2100010400, 1883443112, 1788680591, 1788685103, 5813083723
```

**Comment by mmc46** [comment]
The lineage and type name have been updated in uPNs and mPNs. 
For VP PNs only  the lineage column was updated. 
@lisa-marin you might want to update the type of VP PNs.

**Comment by jefferis** [comment]
Did you validate these cell body fibre assignments @schlegelp?

**Comment by schlegelp** [comment]
I took them directly from neuprint and had only a superficial look. These are fairly distinct CBFs, so I'd be surprised if there were mix ups.

**Comment by schlegelp** [comment]
<img width="563" alt="Screenshot 2020-05-28 at 18 44 46" src="https://user-images.githubusercontent.com/7161148/83175259-879ec000-a113-11ea-9b65-17ebb559e3ab.png">
Checks out for the PNs (bottom view): yellow = l1PN (AVM02^A12); red = l2PN (AVM03^A13)
